update the env templates

diff --git a/backup_script/backup b/backup_script/backup
--- a/backup_script/backup
+++ b/backup_script/backup
@@ -4,10 +4,24 @@
 # Backs up files defined in https://github.com/dani-garcia/vaultwarden/wiki/Backing-up-your-vault
 # Backs up every hour (set in crond for rclone alpine docker)
 
-# Assumes backup directory of /backup and vaultwarden directory of /data
-BACKUP_DIR="/backup"
+# Check if backup directory and vaultwarden data directory are defined
+
+if [ "$BACKUP_ENABLED" = false ]; then
+    echo "Backup disabled; exiting script"
+    exit 1
+fi
+
+if [ -z "$BACKUP_DIR" ]; then
+    echo "Backup dir not defined; exiting script"
+    exit 1
+fi
+
+if [ -z "$BACKUP_DATA_DIR" ]; then
+    echo "Vaultwarden data dir not defined; exiting script"
+    exit 1
+fi
+
 BACKUP_TMP="${BACKUP_DIR}/tmp"
-DATA_DIR="/data"
 
 mkdir -p "${BACKUP_TMP}"
 
@@ -24,7 +38,7 @@ BACKUP_ZIP_DIR="${BACKUP_DIR}/vaultwarden_backup.${DATE_SUFFIX}.zip"
 
 
 # Backup Database
-DB="${DATA_DIR}/db.sqlite3"
+DB="${BACKUP_DATA_DIR}/db.sqlite3"
 if [ -f "$DB" ]; then
     sqlite3 "${DB}" "VACUUM INTO '${DB_BACKUP_DIR}'"
 else
@@ -32,21 +46,31 @@ else
 fi
 
 # Backup Config
-CONFIG="${DATA_DIR}/config.json"
+CONFIG="${BACKUP_DATA_DIR}/config.json"
 if [ -f "$CONFIG" ]; then
     cp -f "${CONFIG}" "${CONFIG_JSON_BACKUP_DIR}"
 else
     echo "Could not find Vaultwarden config.json!"
 fi
 
-# Backup RSA
-zip "${RSA_KEY_BACKUP_DIR}" "${DATA_DIR}"/rsa_key*
-
 # Backup Attachments
-zip -r "${ATTACHMENTS_BACKUP_DIR}" "${DATA_DIR}/attachments"
+ATTACHMENTS="${BACKUP_DATA_DIR}/attachments"
+if [ -d "${ATTACHMENTS}" ]; then
+  zip -r "${ATTACHMENTS_BACKUP_DIR}" ${ATTACHMENTS}
+else
+    echo "Could not find Vaultwarden attachments dir!"
+fi
 
 # Backup Sends
-zip -r "${SENDS_BACKUP_DIR}" "${DATA_DIR}/sends"
+SENDS="${BACKUP_DATA_DIR}/sends"
+if [ -d "${SENDS}" ]; then
+  zip -r "${SENDS_BACKUP_DIR}" ${SENDS}
+else
+    echo "Could not find Vaultwarden sends dir!"
+fi
+
+# Backup RSA (represents current logins, doesn't need to exist)
+zip "${RSA_KEY_BACKUP_DIR}" "${BACKUP_DATA_DIR}"/rsa_key*
 
 # Do overall backup
 cd "${BACKUP_TMP}"
@@ -61,4 +85,4 @@ rm -rf "${BACKUP_TMP}"
 find $BACKUP_DIR/* -mtime +15 -exec rm {} \;
 
 # Do RClone Sync
-rclone --config /config/rclone.conf sync $BACKUP_DIR gdrive:vaultwarden_backup
+rclone --config ${BACKUP_RCLONE_CONFIG} sync ${BACKUP_DIR} ${BACKUP_RCLONE_REMOTE_NAME}:${BACKUP_RCLONE_REMOTE_PATH}
